# Generated by Django 3.2.6 on 2021-09-17 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20210917_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_invita', models.DateTimeField()),
                ('relacion_proyectoi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='registro.proyectos', verbose_name='Proyecto')),
                ('relacion_usuarioi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
            ],
        ),
    ]
