# Generated by Django 3.2.6 on 2021-09-30 01:07

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20210919_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natural',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registro.usuario')),
                ('cedula', models.IntegerField(max_length=10, verbose_name='Cédula')),
                ('genero', models.CharField(choices=[('01', 'Masculino'), ('02', 'Femenico')], default='01', max_length=2)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('registro.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('02', 'Fiscalizaciòn'), ('01', 'Construcción')], default='01', max_length=2),
        ),
    ]
