# Generated by Django 3.2.6 on 2021-11-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20210929_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='natural',
            options={'ordering': ['cedula'], 'verbose_name': 'Persona_Natural', 'verbose_name_plural': 'Personas_Naturales'},
        ),
        migrations.AddField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Proceso'), ('03', 'Fallido'), ('02', 'Adjudicado')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('01', 'Construcción'), ('02', 'Fiscalizaciòn')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_persona',
            field=models.CharField(choices=[('01', 'Natural'), ('02', 'Jurídica')], default='01', max_length=2),
        ),
    ]
