# Generated by Django 3.2.6 on 2021-11-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20211119_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='experiencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='relacion_provinciaU',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='registro.provincia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='natural',
            name='genero',
            field=models.CharField(choices=[('02', 'Femenico'), ('01', 'Masculino')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('03', 'Fallido'), ('01', 'En Proceso'), ('02', 'Adjudicado')], default='01', max_length=2),
        ),
    ]
