# Generated by Django 3.2.6 on 2021-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20211121_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='relacion_provinciaU',
            new_name='provincia_aplica',
        ),
        migrations.AlterField(
            model_name='natural',
            name='genero',
            field=models.CharField(choices=[('01', 'Masculino'), ('02', 'Femenico')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Proceso'), ('03', 'Fallido'), ('02', 'Adjudicado')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('02', 'Fiscalizaciòn'), ('01', 'Construcción')], default='01', max_length=2),
        ),
    ]
