# Generated by Django 3.2.6 on 2021-11-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_auto_20211122_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitaciones',
            name='fecha_invita',
            field=models.DateTimeField(verbose_name='Fecha de invitación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_persona',
            field=models.CharField(choices=[('02', 'Jurídica'), ('01', 'Natural')], default='01', max_length=2),
        ),
    ]
