# Generated by Django 3.2.6 on 2021-11-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_auto_20211122_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='natural',
            name='cedula',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.PositiveIntegerField(default=1, max_length=10, verbose_name='Cedula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='ruc',
            field=models.PositiveIntegerField(default=1, max_length=13, verbose_name='RUC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='natural',
            name='genero',
            field=models.CharField(choices=[('01', 'Masculino'), ('02', 'Femenico')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('02', 'Adjudicado'), ('01', 'En Proceso'), ('03', 'Fallido')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('02', 'Fiscalizaciòn'), ('01', 'Construcción')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_persona',
            field=models.CharField(choices=[('01', 'Natural'), ('02', 'Jurídica')], default='01', max_length=2),
        ),
    ]
