# Generated by Django 3.2.6 on 2021-11-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_auto_20211122_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Proceso'), ('02', 'Adjudicado'), ('03', 'Fallido')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ruc',
            field=models.PositiveBigIntegerField(max_length=13, verbose_name='RUC'),
        ),
    ]
