# Generated by Django 3.2.6 on 2021-11-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_auto_20211122_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='natural',
            name='genero',
            field=models.CharField(choices=[('02', 'Femenico'), ('01', 'Masculino')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Proceso'), ('02', 'Adjudicado'), ('03', 'Fallido')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('02', 'Fiscalizaciòn'), ('01', 'Construcción')], default='01', max_length=2),
        ),
    ]
