# Generated by Django 3.2.6 on 2021-11-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_auto_20211122_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natural',
            name='genero',
            field=models.CharField(choices=[('01', 'Masculino'), ('02', 'Femenico')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('03', 'Fallido'), ('02', 'Adjudicado'), ('01', 'En Proceso')], default='01', max_length=2),
        ),
    ]
