# Generated by Django 3.2.6 on 2021-11-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0019_auto_20211126_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, verbose_name='RUC'),
        ),
    ]
