# Generated by Django 3.2.6 on 2021-11-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0020_auto_20211126_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='provincia_aplica',
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('03', 'Fallido'), ('01', 'En Proceso'), ('02', 'Adjudicado')], default='01', max_length=2),
        ),
    ]
