# Generated by Django 3.2.6 on 2021-12-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0021_auto_20211126_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tel_cel',
            field=models.CharField(default=858, max_length=10, verbose_name='Telf. Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='tel_con',
            field=models.CharField(default=585, max_length=7, verbose_name='Telf. Convencional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('01', 'Oferente'), ('02', 'Técnico')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Proceso'), ('02', 'Adjudicado'), ('03', 'Fallido')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('02', 'Fiscalizaciòn'), ('01', 'Construcción')], default='01', max_length=2),
        ),
    ]
