# Generated by Django 3.2.6 on 2021-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0024_auto_20211204_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('03', 'Fallido'), ('02', 'Adjudicado'), ('01', 'En Proceso')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('01', 'Construcción'), ('02', 'Fiscalizaciòn')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='monto_ref',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto Referencial'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='numero_viviendas',
            field=models.IntegerField(verbose_name='Número de viviendas'),
        ),
    ]
