# Generated by Django 3.2.6 on 2021-12-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0028_auto_20211204_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Proceso'), ('02', 'Adjudicado'), ('03', 'Fallido')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('02', 'Fiscalizaciòn'), ('01', 'Construcción')], default='01', max_length=2),
        ),
    ]
