# Generated by Django 3.2.6 on 2021-12-05 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0029_auto_20211204_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canton',
            name='rel_prov_canton',
            field=models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.RESTRICT, to='registro.provincia'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('03', 'Fallido'), ('01', 'En Proceso'), ('02', 'Adjudicado')], default='01', max_length=2),
        ),
    ]
