# Generated by Django 3.2.6 on 2021-12-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0036_auto_20211223_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitaciones',
            old_name='fecha_invita1',
            new_name='fecha_crea_invita',
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Proceso'), ('03', 'Fallido'), ('02', 'Adjudicado')], default='01', max_length=2),
        ),
    ]
