# Generated by Django 3.2.6 on 2021-12-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0037_auto_20211223_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitaciones',
            name='fecha_invita',
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Proceso'), ('02', 'Adjudicado'), ('03', 'Fallido')], default='01', max_length=2),
        ),
    ]
