# Generated by Django 3.2.6 on 2021-12-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0038_auto_20211223_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitaciones',
            options={'ordering': ['id'], 'verbose_name': 'Invitación', 'verbose_name_plural': 'Invitaciones'},
        ),
    ]
