# Generated by Django 3.2.6 on 2021-12-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0040_auto_20211223_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitados',
            name='estado_invitado',
            field=models.CharField(choices=[('02', 'Invitado'), ('01', 'Adjudicado')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Proceso'), ('03', 'Fallido'), ('02', 'Adjudicado')], default='01', max_length=2),
        ),
    ]
