# Generated by Django 3.2.6 on 2021-12-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0041_auto_20211223_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='Fecha_propuesta',
            field=models.DateTimeField(verbose_name='Fecha de entrega de la propuestas'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('03', 'Fallido'), ('01', 'En Proceso'), ('02', 'Adjudicado')], default='01', max_length=2),
        ),
    ]
