# Generated by Django 3.2.6 on 2021-12-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0042_auto_20211223_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitaciones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Invitación'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('02', 'Adjudicado'), ('03', 'Fallido'), ('01', 'En Proceso')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('01', 'Construcción'), ('02', 'Fiscalizaciòn')], default='01', max_length=2),
        ),
    ]
