# Generated by Django 3.2.6 on 2021-12-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0045_auto_20211224_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('02', 'Adjudicado'), ('01', 'En Proceso'), ('03', 'Fallido')], default='01', max_length=2),
        ),
    ]
