# Generated by Django 3.2.6 on 2022-01-06 14:58

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0046_alter_proceso_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjudica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adjudica', models.DateTimeField(null=True)),
                ('invitacion_ad', models.ForeignKey(null=django.contrib.auth.models.AbstractUser, on_delete=django.db.models.deletion.CASCADE, to='registro.invitaciones')),
            ],
        ),
    ]
