# Generated by Django 3.2.6 on 2022-01-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0047_adjudica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjudica',
            options={'ordering': ['invitacion_ad'], 'verbose_name': 'Adjudicación', 'verbose_name_plural': 'Adjudicaciones'},
        ),
        migrations.AlterField(
            model_name='invitados',
            name='estado_invitado',
            field=models.CharField(choices=[('01', 'Adjudicado'), ('02', 'Invitado')], default='02', max_length=2),
        ),
    ]
