# Generated by Django 3.2.6 on 2022-01-06 15:03

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0048_auto_20220106_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudica',
            name='invitacion_ad',
            field=models.ForeignKey(null=django.contrib.auth.models.AbstractUser, on_delete=django.db.models.deletion.CASCADE, to='registro.invitaciones', verbose_name='Invitación'),
        ),
        migrations.AlterField(
            model_name='invitados',
            name='estado_invitado',
            field=models.CharField(choices=[('02', 'Invitado'), ('01', 'Adjudicado')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('03', 'Fallido'), ('02', 'Adjudicado'), ('01', 'En Proceso')], default='01', max_length=2),
        ),
    ]
