# Generated by Django 3.2.6 on 2022-01-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0049_auto_20220106_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitados',
            name='estado_invitado',
            field=models.CharField(choices=[('01', 'Adjudicado'), ('02', 'Invitado')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('02', 'Adjudicado'), ('03', 'Fallido'), ('01', 'En Proceso')], default='01', max_length=2),
        ),
    ]
