# Generated by Django 3.2.6 on 2022-01-20 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0053_auto_20220106_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudica',
            name='adjudicado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Adjudicado'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Proceso'), ('02', 'Adjudicado'), ('03', 'Fallido')], default='01', max_length=2),
        ),
    ]
