# Generated by Django 3.2.6 on 2022-01-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0055_auto_20220120_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitados',
            name='invitaciones',
            field=models.ForeignKey(db_column='invitaciones_id', on_delete=django.db.models.deletion.CASCADE, to='registro.invitaciones'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('02', 'Adjudicado'), ('03', 'Fallido'), ('01', 'En Trámite')], default='01', max_length=2),
        ),
    ]
