# Generated by Django 3.2.6 on 2022-01-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0056_auto_20220120_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitados',
            options={'ordering': ['invitado'], 'verbose_name': 'Invitado - Adjudicar', 'verbose_name_plural': 'Invitados'},
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Trámite'), ('02', 'Adjudicado'), ('03', 'Fallido')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('02', 'Fiscalizaciòn'), ('01', 'Construcción')], default='01', max_length=2),
        ),
    ]
