# Generated by Django 3.2.6 on 2022-01-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0057_auto_20220120_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitados',
            options={'ordering': ['invitado'], 'verbose_name': 'Invitado', 'verbose_name_plural': 'Invitados'},
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('01', 'Construcción'), ('02', 'Fiscalizaciòn')], default='01', max_length=2),
        ),
    ]
