# Generated by Django 3.2.6 on 2022-01-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0058_auto_20220120_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjudica',
            name='ganador',
        ),
        migrations.AddField(
            model_name='adjudica',
            name='fecha_crea',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invitados',
            name='estado_invitado',
            field=models.CharField(choices=[('01', 'Adjudicado'), ('02', 'Invitado')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('02', 'Fiscalizaciòn'), ('01', 'Construcción')], default='01', max_length=2),
        ),
    ]
