# Generated by Django 3.2.6 on 2022-01-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0059_auto_20220123_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudica',
            name='invitados',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.invitados', verbose_name='Ganador'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('03', 'Fallido'), ('01', 'En Trámite'), ('02', 'Adjudicado')], default='01', max_length=2),
        ),
    ]
