# Generated by Django 3.2.6 on 2022-01-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0061_auto_20220125_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitados',
            name='proceso',
        ),
        migrations.AlterField(
            model_name='invitados',
            name='estado_invitado',
            field=models.CharField(choices=[('02', 'Invitado'), ('01', 'Adjudicado')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('03', 'Fallido'), ('02', 'Adjudicado'), ('01', 'En Trámite')], default='01', max_length=2),
        ),
    ]
