# Generated by Django 3.2.6 on 2022-01-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0062_auto_20220125_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('02', 'Adjudicado'), ('03', 'Fallido'), ('01', 'En Trámite')], default='01', max_length=2),
        ),
    ]
