# Generated by Django 3.2.6 on 2022-01-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0066_auto_20220126_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='dirigido',
            field=models.CharField(choices=[('01', 'Natural'), ('02', 'Jurídica')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('02', 'Adjudicado'), ('01', 'En Trámite'), ('03', 'Fallido')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('02', 'Administrador'), ('02', 'Fiscalizador'), ('01', 'Constructor')], default='01', max_length=2),
        ),
    ]
