# Generated by Django 3.2.6 on 2022-01-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0068_auto_20220128_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('02', 'Adjudicado'), ('03', 'Fallido'), ('01', 'En Trámite')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area_aplica',
            field=models.CharField(choices=[('01', 'Constructor'), ('02', 'Fiscalizador'), ('03', 'Administrador de contrato')], default='02', help_text='Escoja el área', max_length=2),
        ),
    ]
