# Generated by Django 3.2.6 on 2022-01-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0069_auto_20220128_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitados',
            name='estado_invitado',
            field=models.CharField(choices=[('02', 'Invitado'), ('01', 'Adjudicado')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='dirigido',
            field=models.CharField(choices=[('01', 'Natural'), ('02', 'Jurídica')], default='01', max_length=2, verbose_name='Dirigido a'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('02', 'Adjudicado'), ('01', 'En Trámite'), ('03', 'Fallido')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('02', 'Fiscalizador'), ('03', 'Administrador de contrato'), ('01', 'Constructor')], default='01', max_length=2),
        ),
    ]
