# Generated by Django 3.2.6 on 2022-02-04 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0070_auto_20220128_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitados',
            name='estado_invitado',
            field=models.CharField(choices=[('01', 'Adjudicado'), ('02', 'Invitado')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='invitados',
            name='invitaciones',
            field=models.ForeignKey(db_column='invitaciones_id', on_delete=django.db.models.deletion.CASCADE, related_name='rela_invitaciones', to='registro.invitaciones'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('01', 'Constructor'), ('03', 'Administrador de contrato'), ('02', 'Fiscalizador')], default='01', max_length=2),
        ),
    ]
