# Generated by Django 3.2.6 on 2022-02-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0072_auto_20220205_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('01', 'Constructor'), ('03', 'Administrador de contrato'), ('02', 'Fiscalizador')], default='01', max_length=2),
        ),
    ]
