# Generated by Django 3.2.6 on 2022-02-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0073_alter_proceso_tipo_contratacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Trámite'), ('03', 'Fallido'), ('02', 'Adjudicado')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('03', 'Administrador de contrato'), ('01', 'Constructor'), ('02', 'Fiscalizador')], default='01', max_length=2),
        ),
    ]
