# Generated by Django 3.2.6 on 2022-02-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0074_auto_20220205_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('01', 'En Trámite'), ('02', 'Adjudicado'), ('03', 'Fallido')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('01', 'Constructor'), ('02', 'Fiscalizador'), ('03', 'Administrador de contrato')], default='01', max_length=2),
        ),
    ]
