# Generated by Django 3.2.6 on 2022-02-05 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0075_auto_20220205_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitaciones',
            name='fecha_invitacion',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='invitados',
            name='estado_invitado',
            field=models.CharField(choices=[('01', 'Adjudicado'), ('02', 'Invitado')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('03', 'Fallido'), ('01', 'En Trámite'), ('02', 'Adjudicado')], default='01', max_length=2),
        ),
    ]
