# Generated by Django 3.2.6 on 2022-02-05 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0076_auto_20220205_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitaciones',
            name='fecha_invitacion',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('02', 'Adjudicado'), ('01', 'En Trámite'), ('03', 'Fallido')], default='01', max_length=2),
        ),
    ]
