# Generated by Django 3.2.6 on 2022-02-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0077_auto_20220205_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitaciones',
            name='relacion_procesoi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='registro.proceso', unique=True, verbose_name='Proceso'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('03', 'Fallido'), ('01', 'En Trámite'), ('02', 'Adjudicado')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_contratacion',
            field=models.CharField(choices=[('02', 'Fiscalizador'), ('03', 'Administrador de contrato'), ('01', 'Constructor')], default='01', max_length=2),
        ),
    ]
